---
- hosts: localhost
  tasks:
    - name: Grant user Joe read access to a file
      ansible.posix.acl:
        path: ./README.md
        entity: vagrant
        etype: user
        permissions: r
        state: present
